crud operation
anitapise/MI-6-MEAN pull request #131
Opened 2020-08-18 06:58 UTC by sourabh513

2020-08-18 07:13 UTC, Pawan1005 commented on sourabh/project/Node.js-Expess-MongoDB-CRUD/project/models/db.js
> +require('./employee.model');
add new line at the end

2020-08-18 07:13 UTC, Pawan1005 requested changes
add new line at the end

2020-08-19 11:04 UTC, SnehaMakade requested changes
add start script in package.json file and add proper path of mongoDb connection that cluster path dosent work . so change it, and add end line in each file. try to add page at localhost:3000 not at localhost:3000/employee.

2020-09-24 11:30 UTC, Pawan1005 approved these changes

2020-09-24 11:39 UTC, SnehaMakade approved these changes

2020-09-24 12:05 UTC, merged