website assaignment project
anitapise/MI-6-MEAN pull request #79
Opened 2020-05-14 02:29 UTC by ashutoshkumar55

2020-05-14 03:36 UTC, Vedant-29 requested changes
Ashutosh it was mentioned in the rules that u had to make a website with at least 6-7 web pages. but our website only has one HTML and one CSS page. 

pls add more web pages and also add hyperlinks that can link one web page to another.

2020-05-15 10:00 UTC, SnehaMakade commented on ashutosh.txt/css/style.css
> + 	height:0px;
height: after colon there should be space

2020-05-16 03:32 UTC, ashutoshkumar55 commented
okk mam

Thanks

On Fri, May 15, 2020 at 6:02 AM SnehaMakade <notifications@github.com>
wrote:

> *@SnehaMakade* commented on this pull request.
> ------------------------------
>
> In ashutosh.txt/css/style.css
> <https://github.com/anitapise/MI-6-MEAN/pull/79#discussion_r425697659>:
>
> > + 	background-repeat: no-repeat;
> + 	background-position: center;
> + 	height: 100vh;
> + 	background-size: cover;
> + }
> + .clearfix:after{
> + 	content: ".";
> + 	visibility: hidden;
> + 	display: block;
> + 	height:0px;
> + 	clear: both;
> +
> + }
> + .row{
> + 	max-width: 1180px;
> + 	margin:0 auto;
>
> same here add space after (:)this
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/anitapise/MI-6-MEAN/pull/79#pullrequestreview-412512893>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APCLMRC5YAZXDTBBVFK2GQTRRUHJVANCNFSM4NAJDYKQ>
> .
>

2020-05-21 06:09 UTC, Vedant-29 requested changes
Ashutosh redo the website. 
the home page image is not visible.
offers and gift cards have no link.
copying from others is not acceptable so pls make a new website.
no header and footer on the front page.
the logo not visible.
advance ticket booking Is overlapping.
not links in the left bar menu of the booking page.

2020-08-04 11:11 UTC, SnehaMakade requested changes
make correct spelling for commit

2020-08-04 11:20 UTC, ashutoshkumar55 commented
Done mam

On Tue, 4 Aug, 2020, 4:41 PM SnehaMakade, <notifications@github.com> wrote:

> *@SnehaMakade* requested changes on this pull request.
>
> make correct spelling for commit
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/anitapise/MI-6-MEAN/pull/79#pullrequestreview-460715699>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APCLMRGRS2YQEV4LXV4PE4DR67UGDANCNFSM4NAJDYKQ>
> .
>

2020-08-04 11:36 UTC, SnehaMakade requested changes
Do proper indentation
2. in add server entry point in package.json
3.do nodemon install 
4. At localhost:3000 show added employee list

2020-08-04 11:49 UTC, ashutoshkumar55 commented
Okk mam

On Tue, 4 Aug, 2020, 5:06 PM SnehaMakade, <notifications@github.com> wrote:

> *@SnehaMakade* requested changes on this pull request.
>
> Do proper indentation
> 2. in add server entry point in package.json
> 3.do nodemon install
> 4. At localhost:3000 show added employee list
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/anitapise/MI-6-MEAN/pull/79#pullrequestreview-460730905>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APCLMRBN2LUSTSSNXY3CJVLR67XFHANCNFSM4NAJDYKQ>
> .
>

2020-08-07 13:08 UTC, SnehaMakade requested changes
submit button and viewall button is not working so check your routes.

2020-09-24 06:29 UTC, closed without merging

2020-09-24 06:29 UTC, anitapise commented
ashutosh left